# Generated by Django 4.2.5 on 2023-10-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElementoEnUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Usuario_idUsuario', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'elementoenuso',
                'managed': False,
            },
        ),
    ]
