# Generated by Django 4.2.5 on 2023-10-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=100)),
                ('Fecha', models.DateField()),
                ('Mensaje', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'alertas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ElementoPrestado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Encargado', models.CharField(max_length=100)),
                ('Usuario_idUsuario', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'elementoprestado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Elementos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Marca', models.CharField(max_length=100)),
                ('Tipo', models.CharField(max_length=100)),
                ('Observaciones', models.CharField(max_length=100)),
                ('Estado', models.CharField(max_length=100)),
                ('Cantidad', models.PositiveIntegerField()),
                ('Ubicación', models.CharField(max_length=100)),
                ('ElementoEnUso_idElementoEnUso', models.PositiveIntegerField()),
                ('Alertas_idAlertas', models.PositiveIntegerField()),
                ('ElementoPrestado_idElementoPrestado', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'elementos',
                'managed': False,
            },
        ),
    ]
